// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEdT10ZSJFJGeU8IYtqAfzy8Low0g3zF4',
    appId: '1:420315566698:web:52b18b91d668190343f013',
    messagingSenderId: '420315566698',
    projectId: 'ems-5ab21',
    authDomain: 'ems-5ab21.firebaseapp.com',
    storageBucket: 'ems-5ab21.firebasestorage.app',
    measurementId: 'G-JSZTXVVL0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx1GZTg5Bl5JuPj57rpEAZdccmLfOQNwA',
    appId: '1:420315566698:android:1d174fb732dd0d3143f013',
    messagingSenderId: '420315566698',
    projectId: 'ems-5ab21',
    storageBucket: 'ems-5ab21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxqKn6bD5Cwpr-y-5fuYPJliQjRhP_uWI',
    appId: '1:420315566698:ios:c5e97896cdf2fbd843f013',
    messagingSenderId: '420315566698',
    projectId: 'ems-5ab21',
    storageBucket: 'ems-5ab21.firebasestorage.app',
    iosBundleId: 'com.example.emsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxqKn6bD5Cwpr-y-5fuYPJliQjRhP_uWI',
    appId: '1:420315566698:ios:c5e97896cdf2fbd843f013',
    messagingSenderId: '420315566698',
    projectId: 'ems-5ab21',
    storageBucket: 'ems-5ab21.firebasestorage.app',
    iosBundleId: 'com.example.emsProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEdT10ZSJFJGeU8IYtqAfzy8Low0g3zF4',
    appId: '1:420315566698:web:a519a732c97585b843f013',
    messagingSenderId: '420315566698',
    projectId: 'ems-5ab21',
    authDomain: 'ems-5ab21.firebaseapp.com',
    storageBucket: 'ems-5ab21.firebasestorage.app',
    measurementId: 'G-DSTTD66LM7',
  );

}